DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS photo CASCADE;
DROP TABLE IF EXISTS session CASCADE;
